### ISSUE TITLE
Hire a designer

### ISSUE THREAD

**Issue by tonytamsf** [tonytamsf/plumm#3]
I looked at 99designs.com twitter fee to cost out. https://twitter.com/99designs

The logo design projects runs typically at $200, $300.   A site + logo is about $800.  $540 for logo and branding.

Taking this data, doing the work for *plumm* would be a logo, an app design, site and identity would run at least $800.

For @catenotkate to do this as a first time project, since she is not professional just yet,  I was thinking of paying 25% of $800 which is about $160.

I negotiated with @catenotkate and she thought an amateur discount would be 70% and a daughter discount would be 50% would would be $120

I calculated her time spent already was 3 hours at $11 / hour minimum wage was already $33 and she would spend 3 hours for logo, 4 hour for the app and 2 hours for the website which should be another 9 hours of work for a total of $132 if I paid her by the hour.

So @catenotkate and I had a handshake agreement for $80 for the entire job. If the job goes way over the total of 12 hours of work, I will pay her up to $120

**Comment by tonytamsf** [comment]
:+1:

**Comment by catenotkate** [comment]
You sent this to my junk email, just so you know 😅
